import { jsPDF } from "jspdf";

export default function ReportGenerator({

  habits,
  habitsList,

}) {

  const generateReport = () => {

    const doc = new jsPDF();

    const today =
      new Date()
        .toISOString()
        .split("T")[0];

    let totalCompleted = 0;

    Object.values(habits).forEach(
      (day) => {

        Object.values(day).forEach(
          (completed) => {

            if (completed) {

              totalCompleted++;
            }
          }
        );
      }
    );

    const completedToday =
      habitsList.filter(
        (habit) =>
          habits[today]?.[habit]
      ).length;

    /* STRONGEST HABIT */

    let strongestHabit = "";
    let strongestCount = 0;

    habitsList.forEach((habit) => {

      let count = 0;

      Object.values(habits)
        .forEach((day) => {

          if (day[habit]) {

            count++;
          }
        });

      if (
        count >
        strongestCount
      ) {

        strongestCount =
          count;

        strongestHabit =
          habit;
      }
    });

    /* AI INSIGHTS */

    let insight =
      "Consistency needs improvement";

    if (
      totalCompleted >
      50
    ) {

      insight =
        "Excellent productivity and consistency";
    }

    /* PDF CONTENT */

    doc.setFontSize(22);

    doc.text(
      "AI Productivity Report",
      20,
      20
    );

    doc.setFontSize(14);

    doc.text(
      `Generated on: ${today}`,
      20,
      35
    );

    doc.text(
      `Total Habits: ${habitsList.length}`,
      20,
      50
    );

    doc.text(
      `Completed Today: ${completedToday}`,
      20,
      65
    );

    doc.text(
      `Total Completed Tasks: ${totalCompleted}`,
      20,
      80
    );

    doc.text(
      `Strongest Habit: ${strongestHabit}`,
      20,
      95
    );

    doc.text(
      `AI Insight: ${insight}`,
      20,
      110
    );

    doc.text(
      "Generated by Productivity Tracker",
      20,
      140
    );

    doc.save(
      "AI_Productivity_Report.pdf"
    );
  };

  return (

    <div className="bg-gradient-to-br from-slate-800 to-slate-900 border border-slate-700 p-8 rounded-3xl shadow-2xl mt-10">

      <h2 className="text-4xl font-bold mb-6">

        📄 AI Weekly Report

      </h2>

      <p className="text-slate-300 mb-6 text-lg">

        Generate professional AI-powered productivity reports instantly.

      </p>

      <button
        onClick={generateReport}

        className="bg-gradient-to-r from-cyan-500 to-blue-500 px-6 py-4 rounded-2xl font-bold hover:scale-105 transition duration-300"
      >

        Download PDF Report

      </button>

    </div>
  );
}